export const nomes = [
'Almofada de amamentação',
'Andador',
'Babador',
'Banheira',
'Berço',
'Body',
'Bolsa de fraldas',
'Brinquedo',
'Cadeira de balanço',
'Cadeira de alimentação',
'Carrinho de bebê',
'Chocalho',
'Cobertor',
'Colchão de berço',
'Copo de transição',
'Creme para assaduras',
'Cueiro',
'Escova de cabelo',
'Escova de dentes infantil',
'Fralda',
'Fralda de pano',
'Lençol',
'Macacão',
'Mamadeira',
'Manta',
'Móbile',
'Mosquiteiro',
'Naninha',
'Papinha',
'Pente',
'Pomada para assaduras',
'Prato infantil',
'Protetor de berço',
'Rede de berço',
'Sabonete infantil',
'Saída de maternidade',
'Sling',
'Sonda nasogástrica',
'Tapete de atividades',
'Termômetro infantil',
'Toalha de banho',
'Travesseiro de bebê',
'Trocador de fraldas',
'Trocador portátil',
'Vestido',
'Almofada de apoio para amamentação',
'Babá eletrônica',
'Bico de mamadeira',
'Cadeirinha de carro',
'Canguru',
'Carrinho guarda-chuva',
'Chupeta',
'Cobertor de bebê',
'Colher de silicone',
'Conjunto de berço',
'Copo antivazamento',
'Creme hidratante infantil',
'Cueiro de flanela',
'Escorredor de mamadeira',
'Fralda de pano moderna',
'Kit de higiene',
'Lencinho umedecido',
'Macacão de dormir',
'Mantinha de segurança',
'Meias infantis',
'Mochila de bebê',
'Mordedor',
'Nanico',
'Papinha orgânica',
'Perfume de bebê',
'Porta-bebês',
'Protetor solar infantil',
'Rede de descanso',
'Sabonete líquido infantil',
'Saquinho de dormir'
]